application:
  dbType: mysql

server:
  port: 8003
  servlet:
    context-path: /certification

spring:
  application:
    name: euler-service
  # 数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.67.105:3306/openeuler?characterEncoding=utf-8&userSSL=false&serverTimezone=GMT%2B8
    username: openeuleruser
    password: Pasw0d123456!
  config:
    activate:
      on-profile: dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 250MB
  main:
    allow-circular-references: true

# mybatis的相关配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.huawei.it.model.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

euler:
  jwt:
    header: Authorization
    expire: 7200 #token有效时间2小时，秒单位
    secret: ji8n3439n439n43ld9ne9343fdfer49h

# heds s3桶配置
s3:
  endPoint: obs.cn-southwest-2.myhuaweicloud.com
  ak: 3MRQWTR6ZYNZIIDDG5I0
  sk: 1cItLsQFZgveKjJnhBYk3kcvzIKhwt8RQnM62oUi
  bucketName: openeuler-test
  pathStyle: true

heds:
  appId: 127bb61f26ac4516b564baed4cb17e51

# heds ocr服务配置
iam:
  account: ${heds.appId}
  tokenUrl: http://iam.heds-beta2.huawei.com
  secret: WPPZ2bqD7JCwgzzcJUkfnoZNzA/trxYntD2zecNj
  project: 127bb61f26ac4516b564baed4cb17e51
  enterprise: 88888888888888888888888888888888

# 信息提取配置
irs:
  orcUrl: https://apig.heds-beta2.huawei.com/api/image-undir/ocr?projectid=${heds.appId}/ocr
  projectName: Euler
  scene: LicenseIdentify
  irsUrl: https://console.heds-beta2.huawei.com/sir/document/rule-engine/info/info_result

# idaas登录服务配置
idaas:
  clientId: openeulerclient001
  clientSecret: openeuler
  authCodeUrl: https://uniportal.heds-beta2.huawei.com/saaslogin1/oauth2/authorize
  accessTokenUrl: https://uniportal.heds-beta2.huawei.com/saaslogin1/oauth2/accesstoken
  userInfoUrl: https://uniportal.heds-beta2.huawei.com/saaslogin1/oauth2/userinfo
  redirectUrl: https://certification.heds-beta2.huawei.com/certification/auth/callback
  frontCallbackUrl: https://certification.heds-beta2.huawei.com/#/redirectJump
  logoutUrl: https://uniportal.heds-beta2.huawei.com/uniportal1/logout?redirect=http://certification.heds-beta2.huawei.com/certification/auth/logoutCallback
  frontUrl: http://certification.heds-beta2.huawei.com/#/

# 简单通知服务配置
sns:
  appId: ${heds.appId}
  templatedId: B104E4B354C44271AC038BF88B68DCEB
  emailUrl: http://apig.heds-beta2.huawei.com/api/sns/mail/send
  messageUrl: http://apig.heds-beta2.huawei.com/api/sns/mail/send
  xHwAppKey: Fliix82tyRNgsrHYls2G5w==

# api网关
apigw:
  appId: com.huawei.cabg.com
  xHwAppKey: vCUwBMlGsJqgLy12TU/h9g==
  verifyCompanyInfoUrl: https://apigw-beta.huawei.com/api/legalentity/organizationinfo/list?customerName={customerName}&flag=huawei_dm_mc&origSystem=openEuler

upload:
  url: /openeuler/file/

# 兼容性清单证书网关下载地址
downloadUrl:
  domain: http://apig.heds-beta2.huawei.com/api/openeuler/downloadAuthenticate

certificates:
  pdfSavePath: /openeuler/file/